/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1280px",
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1.5rem",
        sm: "2.5rem",
        md: "4rem",
        lg: "6rem",
        xl: "8rem",
      },
    },
    extend: {
      colors: {
        "aetox-bg":                "rgb(var(--aetox-bg-rgb) / <alpha-value>)",
        "aetox-surface-lowest":    "rgb(var(--aetox-surface-lowest-rgb) / <alpha-value>)",
        "aetox-surface-low":       "rgb(var(--aetox-surface-low-rgb) / <alpha-value>)",
        "aetox-surface":           "rgb(var(--aetox-surface-rgb) / <alpha-value>)",
        "aetox-surface-high":      "rgb(var(--aetox-surface-high-rgb) / <alpha-value>)",
        "aetox-surface-highest":   "rgb(var(--aetox-surface-highest-rgb) / <alpha-value>)",
        "aetox-card-bg":           "var(--aetox-card-bg)",
        "aetox-card-border":       "var(--aetox-card-border)",
        "aetox-card-hover":        "var(--aetox-card-hover)",
        "aetox-border":            "rgb(var(--aetox-border-rgb) / 0.1)",
        "aetox-border-strong":     "rgb(var(--aetox-border-rgb) / 0.2)",
        "aetox-text-main":         "rgb(var(--aetox-text-main-rgb) / <alpha-value>)",
        "aetox-text-soft":         "rgb(var(--aetox-text-soft-rgb) / <alpha-value>)",
        "aetox-text-muted":        "rgb(var(--aetox-text-muted-rgb) / <alpha-value>)",
        "aetox-accent":            "rgb(var(--aetox-accent-rgb) / <alpha-value>)",
        "aetox-accent-hover":      "rgb(var(--aetox-accent-rgb) / 0.8)",
        "aetox-accent-subtle":     "rgb(var(--aetox-accent-rgb) / 0.1)",
        "aetox-error":             "rgb(var(--aetox-error-rgb) / <alpha-value>)",
        "aetox-error-surface":     "rgb(var(--aetox-error-rgb) / 0.1)",
        "aetox-value":             "rgb(var(--aetox-value-rgb) / <alpha-value>)",
        "aetox-aura-1":            "rgb(var(--aetox-accent-rgb) / <alpha-value>)",
        "aetox-grid-line":         "rgb(var(--aetox-border-rgb) / 0.05)",
      },
      fontSize: {
        "fluid-h1": ["clamp(2rem, 4vw + 1rem, 4.5rem)",  { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "fluid-h2": ["clamp(1.5rem, 3vw + 1rem, 3rem)",    { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "600" }],
        "fluid-h3": ["clamp(1.25rem, 2vw + 1rem, 2rem)",    { lineHeight: "1.2",  fontWeight: "600" }],
        "fluid-h4": ["clamp(1.125rem, 1.5vw + 1rem, 1.5rem)", { lineHeight: "1.4", fontWeight: "500" }],
        "fluid-p":  ["clamp(1rem, 1vw + 0.75rem, 1.125rem)", { lineHeight: "1.6",  fontWeight: "400" }],
        "fluid-sm": ["clamp(0.875rem, 0.5vw + 0.75rem, 1rem)", { lineHeight: "1.5", fontWeight: "400" }],
        "fluid-label": ["clamp(0.75rem, 0.2vw + 0.7rem, 0.8125rem)", { lineHeight: "1", fontWeight: "600", letterSpacing: "0.05em" }],
      },
      fontFamily: {
        display: ["var(--font-ibm-plex-thai)", "var(--font-ibm-plex-sans)", "sans-serif"],
        sans: ["var(--font-ibm-plex-thai)", "var(--font-ibm-plex-sans)", "sans-serif"],
      },
      borderRadius: {
        sm:      "0.125rem",
        DEFAULT: "0.25rem",
        md:      "0.375rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        xs:     "0.5rem",
        sm:     "1rem",
        md:     "1.5rem",
        lg:     "2.5rem",
        xl:     "4rem",
        gutter: "1.5rem",
        margin: "2rem",
      },
      backgroundImage: {
        "aetox-blueprint": "linear-gradient(var(--aetox-grid-line) 1px, transparent 1px), linear-gradient(90deg, var(--aetox-grid-line) 1px, transparent 1px)",
      },
      boxShadow: {
        "aetox-card": "var(--aetox-shadow-card)",
        "aetox-glow": "var(--aetox-shadow-glow)",
        "aetox-inset": "inset 0 1px 0 var(--aetox-border)",
      },
      animation: {
        "aetox-breathe": "aetox-breathe 4s ease-in-out infinite",
        "aetox-fade-in": "aetox-fade-in 0.4s ease-out forwards",
      },
      keyframes: {
        "aetox-breathe": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%":      { opacity: "0.6", transform: "scale(0.97)" },
        },
        "aetox-fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};